# Generated by Django 3.0.3 on 2021-04-25 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Location', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='distributor',
            unique_together={('user', 'location')},
        ),
    ]
